### ISSUE TITLE
" No such file or directory" on Windows Host

### ISSUE THREAD

**Issue by tsotnet** [adrienkohlbecker/vagrant-fsnotify#11]
Hi @adrienkohlbecker,

I installed the plugin on Windows host as described in README.md. Unfortunately I get the following error when running "vagrant fsnotify":

```
PS C:\Users\tsotne\Desktop\6.148> vagrant fsnotify
==> default: fsnotify: Watching /c/Users/tsotne/Desktop/6.148/
C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/adapter/config.rb:17:in `realpath': No such file or directory - /c (Errno::ENOENT)
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/adapter/config.rb:17:in `realpath'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/adapter/config.rb:17:in `block in initialize'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/adapter/config.rb:16:in `map'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/adapter/config.rb:16:in `initialize'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/backend.rb:21:in `new'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/backend.rb:21:in `initialize'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/listener.rb:46:in `new'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen/listener.rb:46:in `initialize'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen.rb:36:in `new'
        from C:/Users/tsotne/.vagrant.d/gems/gems/listen-3.0.5/lib/listen.rb:36:in `to'
        from C:/Users/tsotne/.vagrant.d/gems/gems/vagrant-fsnotify-0.2.0/lib/vagrant-fsnotify/command-fsnotify.rb:119:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```

It seems as if the plugin is trying to find /c directory, which doesn't exist as the host has Windows installed on it, so the correct path would be C:/

I tried uninstalling and installing the plugin, restarting the VM, but nothing helped. I would appreciate your help.

Thanks.

**Comment by adrienkohlbecker** [comment]
Hi,
Thanks for reporting this issue. I've never actually tested the gem on Windows (I don't have Windows machines).
I'll try to set up a VM next week to check it out, feel free to ping me if I forget.
Best,

**Comment by tsotnet** [comment]
Sure, thanks for looking into this!

**Comment by tsotnet** [comment]
Okay so since I don't know ruby, I avoided looking into this myself. But, I explored command-fsnotify.rb today and found that just removing the following four lines solved the problem for me:

`
            if Vagrant::Util::Platform.windows?
              # rsync for Windows expects cygwin style paths, always.
              hostpath = Vagrant::Util::Platform.cygwin_path(hostpath)
            end
`
I'm not using Cygwin. This didn't allow path to change from C:/Users/tsotne/Desktop/6.148 to /c/Users/tsotne/Desktop/6.148/
