### ISSUE TITLE
100% CPU usage?

### ISSUE THREAD

**Issue by toobulkeh** [adrienkohlbecker/vagrant-fsnotify#13]
While this is a workable solution, it's still sitting on 100% of a CPU on a mac OSX (10.11.3) host.

Any ideas why this would be the case, or would it be useful for me to trace?

**Comment by adrienkohlbecker** [comment]
Mmm, I don't have any ideas, this would need some investigation. Maybe something to do with the listen gem? I know it can fallback to polling depending on the use case. Would you mind sharing a bit more about your setup?

**Comment by toobulkeh** [comment]
I wouldn't mind at all -- what would be useful to share?

**Comment by toobulkeh** [comment]
Took me awhile to figure this out, but for posterity:

Turn on logging at the Listen level:
`LISTEN_GEM_DEBUGGING=1`

OR

Turn on logging at the vagrant plugin level:
`VAGRANT_LOG=info vagrant fsnotify`

From there you can get output of what the process is doing to take so long.

In my case, I had not muted all my git directories, which make lots of file changes in places where I wouldn't normally expect them.

My Vagrantfile is now:
`config.vm.synced_folder ".", "/vagrant", fsnotify: true, exclude: ["*.git/", "*tmp/", "*cache/", "*node_modules/", "*bower_components/"]`

And my CPU is happy.
