### ISSUE TITLE
Notify on added (and removed?) files

### ISSUE THREAD

**Issue by leafac** [adrienkohlbecker/vagrant-fsnotify#2]
Hi, @adrienkohlbecker.

First of all, thank you very much for creating this tool. It's exactly what I was looking for. I was considering writing something like it myself, so I really appreciate your work.

Is there a reason for `vagrant-fsnotify` to ignore the added and removed file events?

It seems like added events could be treated the same as changed events, just `touch` the files.

Removed events could trigger a `touch` followed by a `rm`. This is a hack, I admit. But for my applications it would get the job done. I don't think this would be a nice default behavior, but something we could opt in. For example, in the `Vagrantfile` I could pass in the option `fsnotify: :include_removed_events`.

I'd be more than happy to send a PR if you think the feature is worth it.

Other than that, the tool is great!

Thanks!

**Comment by adrienkohlbecker** [comment]
Thanks for reporting this !
I would gladely merge your PR if you push one :)

**Comment by leafac** [comment]
Hi, @adrienkohlbecker.

I started working on this, but I don't have anything to show, yet (besides [this unrelated PR](https://github.com/adrienkohlbecker/vagrant-fsnotify/pull/5)).

I was thinking more about the feature and I want to propose a more structured API.

The `:fsnotify` option on the `Vagrantfile` could take an array of symbols among the following options:

- `:modified`: forward modified file events with `touch`.
- `:added`: forward add file events with `touch`.
- `:removed`: forward removed file events with `touch`+`rm`.

Alternatively, `fsnotify: true` would still work and would mean the same as `[:modified, :added, :removed]`. I believe this is the most common use-case (at least it is for me) and is the most intuitive behavior (except for the `touch`-`rm` hack).

This would become an incompatible change, though, requiring us to bump a minor version (e.g. `0.1.0`). It would be a major bump if we were `1.0`, but we aren't yet.

What do you think about this?

Best.

**Comment by adrienkohlbecker** [comment]
What would be the use case of changing which events to listen to ? Do you have any example in mind?
I'd rather keep things simple with the configuration, if it supports a majority of use cases.

I'm ok to bump to `0.1.0` though

Regarding `touch+rm`, it's not a much bigger hack than `touch` :smile: I'm just wondering if there would be any side effects

**Comment by leafac** [comment]
The purpose of the configuration switches is to enable use cases in which some of the filesystem events would be undesirable. In particular, file removal events with `touch`+`rm` could cause problems as two filesystem notifications are going to be sent. For some applications, it would be better to ignore those events altogether. I can't name an example, though.

On the other hand, I share your point of view of valuing simplicity in configuration. Thus the proposal to keep `true` as a enable-all switch. Most users can use it and never bother with the switches. For those that want, they would be there.

I'm going to implement whatever you think is the better fit for the project. Please, let me know your preference.

**Comment by adrienkohlbecker** [comment]
Hello,
Ok, I guess having a choice is better :) Go with whatever you feel best

**Comment by adrienkohlbecker** [comment]
Fixed by #6
