### ISSUE TITLE
How to auto run vagrant fsnotify?

### ISSUE THREAD

**Issue by gandra** [adrienkohlbecker/vagrant-fsnotify#21]
Is it possible to auto start fsnotify?
This plugin works great. The only thong I miss is auto start.  At the moment I have to run manually `vagrant fsnotify` each time after `vagrant up`?

**Comment by cmrn** [comment]
Yes! The work in PR #20 adds this functionality.

**Comment by adrienkohlbecker** [comment]
Hi @gandra, sorry for the late reply.
You can achieve this by using the triggers option in your vagrantfile:
```ruby
config.trigger.after :up do
  run "vagrant fsnotify"
end
```
See also https://www.vagrantup.com/docs/triggers/
