### ISSUE TITLE
Why touch -a instead of just touch ?

### ISSUE THREAD

**Issue by caug-rodriguez** [adrienkohlbecker/vagrant-fsnotify#22]
My node server doesn't trigger a rebuild when the touch -a is performed but it does work with touch alone. Is there a reason to use the "-a" option?

**Comment by lammensj** [comment]
I'm having the same issue: `touch -a` only adjusts the access time, but that is not happening inside my vagrant machine. Not sure if it's caused by nfs or something else... Maybe somebody else has a suggestion?

**Comment by adrienkohlbecker** [comment]
Hi @caug-rodriguez @lammensj
Sorry for the late reply.
We have a PR for a fix to this here https://github.com/adrienkohlbecker/vagrant-fsnotify/pull/28 will let you know when it is released.

**Comment by adrienkohlbecker** [comment]
Closing as version 0.3.1 is up on rubygems and includes the fix for this
