### ISSUE TITLE
Interested in project. Is it dead. Should it be forked?

### ISSUE THREAD

**Issue by jkugler** [adrienkohlbecker/vagrant-fsnotify#24]
Hello! I came across this project today. It sounds like it would be very useful for our needs, but also appears to have issues with recent Vagrant versions, as well as having missing features (See #20). Is this project dead? Should it be forked? Is there hope of reviving it?

**Comment by Fendrian** [comment]
I've been using this for some time as my preferred method of getting filesystem events into a vagrant box on both Windows and OS X systems. I've trialled a few different solutions, and none have worked nearly as well.

I personally have never had any issues installing or using this plugin on any version of Vagrant, however the method used to prevent duplicate filesystem events (stop watching any changed file for a few seconds) does break down sometimes when a large number of changes trigger (such as switching branches), so I've found that explicitly running it in its own window allows me to easily restart it on the rare occasions that it gets stuck, and also the running feed of changed files has been useful for debugging on occasion.

So, while I am not this project's creator and can't comment on it being dead or not, I do personally find it to be extremely useful in its current state. I don't currently see any clear path forward with any improvements (I would not use a daemon even if it were available), but I would be happy to assist where I can if any clear improvements were proposed.

**Comment by adrienkohlbecker** [comment]
Hi @jkugler and @Fendrian.

>  I don't currently see any clear path forward with any improvements (I would not use a daemon even if it were available), but I would be happy to assist where I can if any clear improvements were proposed.

This is currently my state of mind regarding this project. I follow the issues and can merge and release changes. 
I must admit though I haven't been as reactive with issues as I should have these past couple years
So, to be clear, this repo is not dead, and I'm happy to review PRs for improvements, but I don't have any improvement planned myself

I've also just now updated the issue #20 you're mentioning with a path forward
