### ISSUE TITLE
vagrant-fsnotify 0.3.0 problem with vagrant v2.4.4

### ISSUE THREAD

**Issue by Levon770** [adrienkohlbecker/vagrant-fsnotify#27]
The vagrant-fsnotify not working properly with vagrant version 2.4.4. the plugin see the changes on windows 10 host, but not provide the changes to guest virtual machine (ubuntu 18.04), where I am running angular. before vagrant version update it works perfectly. is there any known issues and solutions

**Comment by Levon770** [comment]
suggested a change via pull request

**Comment by Fendrian** [comment]
Unfortunately the last change to this project was three years ago, so as has been mentioned in other issues it appears to be effectively dead. I'd be happy to be proven wrong there, but there's currently no evidence to the contrary.

I love this plugin, so I've forked/copied/renamed it (keeping commit history and contributions!) to what I'm calling [vagrant-fsevents](https://github.com/Fendrian/vagrant-fsevents). Not sure if that's the correct etiquette for this sort of thing, but two packages can't have the same name on RubyGems, so for continued development the name had to change somehow.

Anyway, if your pull request gets accepted here that'd be great, but if not I'm happy for you to submit a pull request to vagrant-fsevents. I've been meaning to make that change (it was the impetus for me to finally spend a few days getting back into Ruby in the first place) but got distracted refactoring and linting and haven't gotten to it yet.

**Comment by Levon770** [comment]
@Fendrian I share your approach and I'll keep an eye on your repo.

**Comment by adrienkohlbecker** [comment]
Hi @Fendrian !
It's great that you want to improve the plugin and I thank you for it. Feel free to keep on with your fork, but also know that I'll gladly review and merge any PR you send my way. 
I haven't found the time to work on the current open issues myself, especially since I don't use the plugin much if at all anymore, but I still get notified and can merge and release proposed changes.

**Comment by adrienkohlbecker** [comment]
Discussing the original issue with @Levon770 in the PR here https://github.com/adrienkohlbecker/vagrant-fsnotify/pull/28

**Comment by adrienkohlbecker** [comment]
Closing as version 0.3.1 is up on rubygems and includes #28
