### ISSUE TITLE
Dependency hell (a.k.a the strangest bug ever)

### ISSUE THREAD

**Issue by leafac** [adrienkohlbecker/vagrant-fsnotify#9]
Hi, @adrienkohlbecker.

After a few more hours debugging the problem [mentioned
here](https://github.com/adrienkohlbecker/vagrant-fsnotify/pull/8), I still
don't have a solution, but I know a little more about it.

The problem
-----------

When running `vagrant-fsnotify` the user gets the following output:

```
D, [2015-07-05T17:24:29.520047 #42654] DEBUG -- : Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
==> default: fsnotify: Watching /Users/leafac/Documents/code/leafac/vagrant-fsnotify/
D, [2015-07-05T17:24:31.167105 #42654] DEBUG -- : Adapter: considering TCP ...
D, [2015-07-05T17:24:31.167243 #42654] DEBUG -- : Adapter: considering polling ...
D, [2015-07-05T17:24:31.167296 #42654] DEBUG -- : Adapter: considering optimized backend...
/Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/calls.rb:48:in `check': wrong number of arguments (2 for 1) (ArgumentError)
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/calls.rb:26:in `dispatch'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:45:in `value'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-0.17.0/lib/celluloid/proxy/sync.rb:40:in `method_missing'
	from /Users/leafac/.vagrant.d/gems/gems/listen-2.8.6/lib/listen/listener.rb:206:in `_init_actors'
	from /Users/leafac/.vagrant.d/gems/gems/listen-2.8.6/lib/listen/listener.rb:87:in `block in <class:Listener>'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-fsm-0.20.0/lib/celluloid/fsm.rb:176:in `instance_eval'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-fsm-0.20.0/lib/celluloid/fsm.rb:176:in `call'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-fsm-0.20.0/lib/celluloid/fsm.rb:129:in `transition_with_callbacks!'
	from /Users/leafac/.vagrant.d/gems/gems/celluloid-fsm-0.20.0/lib/celluloid/fsm.rb:97:in `transition'
	from /Users/leafac/.vagrant.d/gems/gems/listen-2.8.6/lib/listen/listener.rb:100:in `start'
	from /Users/leafac/.vagrant.d/gems/gems/vagrant-fsnotify-0.1.1/lib/vagrant-fsnotify/command-fsnotify.rb:132:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /Users/leafac/.vagrant.d/gems/gems/vagrant-fsnotify-0.1.1/lib/vagrant-fsnotify/command-fsnotify.rb:131:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

The cause
---------

When the user ran `vagrant plugin install vagrant-fsnotify`, besides installing
`vagrant-fsnotify`, Vagrant also installed a new version of Celluloid. Vagrant
comes with Celluloid 0.16.0 and installing the plugin installed Celluloid
0.17.0.

When there's the chance, Vagrant chooses to load the newest version of the
dependency. As you can see from the stacktrace above, the plugin doesn't work
with Celluloid 0.17.0.

Possible explanations
---------------------

`vagrant-fsnotify` no longer depends on anything on the `.gemspec`. It's very
strange that other dependencies are being installed, then.

Under the hood, Vagrant uses Bundler to manage the dependencies, which in turn
depends on RubyGems. It so happens that the new version of Celluloid is *not*
installed if you do the following:

1. Install `vagrant-fsnotify` with `gem install vagrant-fsnotify`.

2. Create a `Gemfile` with that declares `vagrant-fsnotify` and run `bundle
   install`. Celluloid isn't installed or mentioned on the `Gemfile.lock`.

3. Build the gem from source by cloning this repository and running `gem build
   vagrant-fsnotify.gemspec`; and then installing it with `vagrant plugin
   install vagrant-fsnotify-0.1.1.gem`.

I read the relevant part of the Vagrant code that deals with installing plugins
through Bundler. Nothing fancy happens there. They just generate a `Gemfile`
with the plugins listed.

Testing
-------

Check the `~/.vagrant.d/gems/gems/` folder after installing the
plugin. Celluloid shouldn't be there at all. You can remove the whole
`~/.vagrant.d` directory to test with a fresh install, if you don't care about
loosing your installed plugins.

The ultimate test
-----------------

Debugging this was hard, because the problem only happens when installed from
RubyGems. So I decided to rename everything and publish
[vagrant-fsnotify-tmp](https://github.com/leafac/vagrant-fsnotify/tree/tmp) to
RubyGems with `gem push vagrant-fsnotify-tmp-0.1.4.gem`.

To my surprise, this version of the gem works (!) It doesn't install Celluloid
0.17.0 and the command line tool works. If you want to test yourself, rename the
`:fsnotify` to `:fsnotify_tmp` on your `Gemfile` and run `vagrant fsnotify-tmp`.

---

On a related note, merging [this
PR](https://github.com/adrienkohlbecker/vagrant-fsnotify/pull/8) was the right
call. [Vagrant
documentation](https://docs.vagrantup.com/v2/plugins/packaging.html) says:

> Do not depend on Vagrant for your gem. Vagrant is no longer distributed as a
> gem, and you can assume that it will always be available when your plugin is
> installed.

---

Finally, the plugin is broken and anyone who installs it needs to get rid of the
whole `~/.vagrant.d` directory to restore a working state. This is terrible and
I think we should yank versions `0.1.0` and `0.1.1` from RubyGems until we
figure this out to prevent further damage.

You can do that by running `gem yank vagrant-fsnotify -v 0.1.0 && gem yank
vagrant-fsnotify -v 0.1.1`.

Also, for the next attempt, I suggest we release a beta version first :)

---

This is one of the weirdest bugs I've ever seen. Any help is much appreciated.

---

Best.

**Comment by adrienkohlbecker** [comment]
Ok, thanks for the write-up.
I'll try to free some time later this week to check it out, without guarantee (we're in the middle of a product launch over here)
In the meantime I've yanked the gems as you suggested, good call
